### PR TITLE
Format Information

### PR DESCRIPTION
**Pull request by ghost**
This information is based off of @Cracko298's data given.
The proper format for what you're describing is backwards ETC2_RGBA8 data.
That is how most games from Consoles read data, from the end towards the beginning of the file.

Hense why it looks "weird"

### CODE REVIEW

**Comment by Cracko298** [comment]
Why was I mentioned in this?

**Comment by VoxelBill** [comment]
After looking at Cracko298's documentation I can see where you got that but i didn't see a mention of multiple `Color Types` like i have found unless I missed something. 

All the code and documentation i have is what I managed to figure out myself I didn't go off anyone else's information when I made this as at the time I couldn't find any.

I wasn't aware that consoles read the data from the end to the beginning but even so I don't think any code will have to change as it works fine with all my test files.

Does using the `ETC2_RGBA8` assume im reading from the end of the file to the beginning? Because from my testing reading the pixels in ARGB order caused the image to not look correct which is why I thought it was ABGR order, but i can see that possibly being different if i read from the end of the file.

**Comment by Cracko298** [comment]
I'm not in this conversation, I don't even know why I was mentioned.
However, I should interject, the 3ds console reads from eof towards the beginning of the file for some formats, which can range from as we see right now with some images to savegames.

That's why the image is flipped upside down, so the console presumably reads it rightside up.

ColorTypes shouldn't matter. However, due to the Alpha Bytes either being on (0xFF meaning color in RGB format in the Bytes corresponding after it, or < 0xFF meaning that the pixel is fully transparent and ignores the RGB values after it).

I'm unsure about what the ColorTypes are, as I didn't read what anything on the Markdown document myself.

**Comment by ghost** [comment]
Ooooh somebody is mad

**Comment by VoxelBill** [comment]
The color formats i mentioned are:

* Color Type `00 00 00 00` (0) = 4 byte ABGR texture
* Color Type `01 00 00 00` (1) = 3 byte BGR texture
* Color Type `02 00 00 00` (2) = 2 byte HighColor (16-bit RGBA 5551) texture.

This PR is saying color type 0 should be ARGB which im not sure if thats correct or not but if the program is meant to read from the end to the beginning i can see how that would change the results I got.

**Comment by VoxelBill** [comment]
Also I just want to mention i didn't copy any of your information Cracko298.

I annualized the binary file and did research to create the documentation I have.
I haven't even heard of you until today, and I didn't mean any harm to you from creating similar documentation. 
If you would like to talk to me about this more I could give you my Discord and we can talk there.

**Comment by Cracko298** [comment]
I ain't too worried about it, even if it was.
Confusion is probably from the 3+ different texture formats/color-modes the game uses (all of which seem to be some form of ETC2 or ETC1).

**Comment by VoxelBill** [comment]
Yeah probably.

When I have time I will update the library to parse the file how the 3DS handles it starting at the end of the file.
I will then merge this and add the updated info is from your docs with a link.

**Comment by VoxelBill** [comment]
So looks like changing the library to read the pixel data from the end to the beginning is going to a slightly more complicated change to make as Java (at least with what im using) doesn't provide an easy was to read backwards.

So im going to just push my changes to docs and consider this completed.

There are some extra things I added that this PR didn't include so this will likely just be closed as my changes include the info added from this as well.

**Comment by VoxelBill** [comment]
Closing as complete with latest push.

**Pull request closed without merging**
